My Application: FPC Class Reference
FPC Class Reference
FPC class based off Camera class.
#include <FPC.h>
Public Member Functions
FPC ()
~FPC ()
virtual void Init (const Vector3 &pos, const Vector3 &target, const Vector3 &up, bool _allowFlight=false)
Initialize default camera position, target, and tilt.
virtual void Set (const Vector3 &pos, const Vector3 &target, const Vector3 &up, bool _allowFlight=false)
Sets camera position, target and up vectors.
virtual void SetSensitivity (float _mouseSensX, float _mouseSensY)
Sets the mouse sensitivity of the camera.
virtual void SetSpeed (float _moveSpeed, float _rotSpeed)
Sets the camera default moving speed.
virtual void SetFlight (bool _allowFlight=true)
Sets whether the player can fly.
virtual void Update (double dt, vector< CObjects > list)
Camera controls.
virtual void Reset ()
Resets camera to default camera position.
Public Member Functions inherited from Camera
Camera ()
Reset Camera function call.
~Camera ()
virtual void Init (const Vector3 &pos, const Vector3 &target, const Vector3 &up)
Update camera position.
virtual void Update (double dt)
Update based on key pressed.
Data Fields
bool move
Data Fields inherited from Camera
Vector3 position
Vector3 target
Vector3 up
Private Attributes
Vector3 defaultPosition
Vector3 defaultTarget
Vector3 defaultUp
float defaultMoveSpeed
float defaultRotSpeed
float pitchDist
bool allowFlight
float mouseSensX
float mouseSensY
bool collideW
bool collideS
bool collideA
bool collideD
Detailed Description
FPC class based off Camera class.
Class FPC:
Definition at line 25 of file FPC.h.
Constructor & Destructor Documentation
FPC::FPC ()
Definition at line 14 of file FPC.cpp.
FPC::~FPC ()
Definition at line 18 of file FPC.cpp.
Member Function Documentation
void FPC::Init (const Vector3 & pos, const Vector3 & target, const Vector3 & up, bool _allowFlight = false) virtual
Initialize default camera position, target, and tilt.
Parameters
pos - camera position
target - camera target
up - camera up direction
_allowFlight - controls whether players can take to the skies when moving forward and looking up
Definition at line 33 of file FPC.cpp.
References allowFlight, collideA, collideD, collideS, collideW, Vector3::Cross(), defaultPosition, defaultTarget, defaultUp, move, Vector3::Normalize(), Vector3::Normalized(), pitchDist, Camera::position, SetSensitivity(), SetSpeed(), Camera::target, and Vector3::y.
void FPC::Reset () virtual
Resets camera to default camera position.
Reimplemented from Camera.
Definition at line 321 of file FPC.cpp.
References defaultPosition, defaultTarget, defaultUp, pitchDist, Camera::position, Camera::target, and Camera::up.
Referenced by Update().
void FPC::Set (const Vector3 & pos, const Vector3 & target, const Vector3 & up, bool _allowFlight = false) virtual
Sets camera position, target and up vectors.
Parameters
pos - camera position
target - camera target
up - camera up direction
_allowFlight - controls whether players can take to the skies when moving forward and looking up
Definition at line 62 of file FPC.cpp.
References allowFlight, Vector3::Cross(), Vector3::Normalize(), Vector3::Normalized(), Camera::position, Camera::target, and Vector3::y.
void FPC::SetFlight (bool _allowFlight = true) virtual
Sets whether the player can fly.
Parameters
_allowFlight - controls whether players can take to the skies when moving forward and looking up
Definition at line 112 of file FPC.cpp.
References allowFlight.
void FPC::SetSensitivity (float _mouseSensX, float _mouseSensY) virtual
Sets the mouse sensitivity of the camera.
Parameters
_mouseSensX - horizontal mouse sensitivity
_mouseSensY - vertical mouse sensitivity
Definition at line 82 of file FPC.cpp.
References mouseSensX, and mouseSensY.
Referenced by Init().
void FPC::SetSpeed (float _moveSpeed, float _rotSpeed) virtual
Sets the camera default moving speed.
Parameters
_moveSpeed - default movement speed for the camera
_rotSpeed - default rotation speed for the camera (when using arrow keys)
Definition at line 100 of file FPC.cpp.
References defaultMoveSpeed, and defaultRotSpeed.
Referenced by Init().
void FPC::Update (double dt, vector< CObjects > list) virtual
Camera controls.
Definition at line 122 of file FPC.cpp.
References allowFlight, collideA, collideD, collideS, collideW, Collision(), Vector3::Cross(), defaultMoveSpeed, defaultRotSpeed, Application::GetMouseinput(), Application::IsKeyPressed(), mouseSensX, mouseSensY, move, Vector3::Normalize(), Vector3::Normalized(), pitchDist, Camera::position, Reset(), Application::returnWindowSize(), Application::SetMouseinput(), Mtx44::SetToRotation(), Camera::target, Camera::up, Vector3::x, Vector3::y, and Vector3::z.
Field Documentation
bool FPC::allowFlight private
Definition at line 53 of file FPC.h.
Referenced by Init(), Set(), SetFlight(), and Update().
bool FPC::collideA private
Definition at line 59 of file FPC.h.
Referenced by Init(), and Update().
bool FPC::collideD private
Definition at line 59 of file FPC.h.
Referenced by Init(), and Update().
bool FPC::collideS private
Definition at line 59 of file FPC.h.
Referenced by Init(), and Update().
bool FPC::collideW private
Definition at line 59 of file FPC.h.
Referenced by Init(), and Update().
float FPC::defaultMoveSpeed private
Definition at line 46 of file FPC.h.
Referenced by SetSpeed(), and Update().
Vector3 FPC::defaultPosition private
Definition at line 43 of file FPC.h.
Referenced by Init(), and Reset().
float FPC::defaultRotSpeed private
Definition at line 47 of file FPC.h.
Referenced by SetSpeed(), and Update().
Vector3 FPC::defaultTarget private
Definition at line 44 of file FPC.h.
Referenced by Init(), and Reset().
Vector3 FPC::defaultUp private
Definition at line 45 of file FPC.h.
Referenced by Init(), and Reset().
float FPC::mouseSensX private
Definition at line 56 of file FPC.h.
Referenced by SetSensitivity(), and Update().
float FPC::mouseSensY private
Definition at line 57 of file FPC.h.
Referenced by SetSensitivity(), and Update().
bool FPC::move
Definition at line 31 of file FPC.h.
Referenced by Init(), and Update().
float FPC::pitchDist private
Definition at line 50 of file FPC.h.
Referenced by Init(), Reset(), and Update().
The documentation for this class was generated from the following files:
Application/Source/FPC.h
Application/Source/FPC.cpp