My Application: SceneAssignment Class Reference
SceneAssignment Class Reference
SceneAssignment class.
#include <SceneAssignment.h>
Public Member Functions
SceneAssignment ()
~SceneAssignment ()
void InitLevel1 ()
Initialize the walls and doors used for level 1 /*.
void InitLevel2 ()
Initialize the walls and doors used for level 2 /*.
void InitObjects ()
Initialize all the objects that are going to be used in the program /*.
void InitExtSkybox ()
Initialize the quards that produce the landscape ooutside of the suermarket /*.
void InitCollision ()
Initialize add some collision for most of our large objects /*.
void InitAI ()
Initialize the combined parts of the body for our scripted movement NPCs /*.
void InitModelBlue ()
Initialize the individual parts of the body for our blue NPC /*.
void InitModelOrange ()
Initialize the individual parts of the body for our orange NPC /*.
void InitModelPink ()
Initialize the individual parts of the body for our pink NPC /*.
void InitModelRed ()
Initialize the individual parts of the body for our red NPC /*.
void InitModelYellow ()
Initialize the individual parts of the body for our yellow NPC /*.
void UpdateViewMode (double dt)
Update all of our different viewmode such as wireframe mode /*.
void UpdateDoor (double dt)
Update the exit and entrance door for the player and moving NPCs to enter and exit /*.
void UpdateLift (double dt)
Update the lift movement and the lift door also /*.
void UpdateLight (double dt)
Update the light effect when there is fire alarm /*.
void UpdateModel (double dt)
void UpdateTravel (double dt)
Update the player and moving NPCs to be able to use the travelator /*.
void UpdateModelGlenn (double dt)
Walking animation of moving NPCs /*.
void UpdateStaticAIGlenn (double dt)
void RenderLevel1 ()
Render the walls and doors for level 1 /*.
void RenderLevel2 ()
Render out the walls and doors for level 2 /*.
void RenderChar ()
Render static NPCs at the cash register /*.
void RenderLargeObjects ()
Render out all the large objects such as the shelves and cashier for both levels /*.
void RenderRightColumn ()
Render the cereal boxes at the right column of level 2 /*.
void RenderLeftColumn ()
Render the cereal boxes at the leftr column of level 2 /*.
void RenderMiddleColumn ()
Render the cereal boxes at the middle column of level 2 /*.
void RenderSmallObjects ()
Render the fruits and ice cream at level 1 /*.
void RenderModels ()
Render call the render model functions at the top in here like a compile /*.
void RenderOut_Skybox ()
Render the exterior skyboxes,moutains and houses outside of the supermarket /*.
void RenderText (Mesh *mesh, std::string text, Color color)
Render a function that enable text rendering in the world space /*.
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
Render a function that enable text rendering on screen /*.
void RenderMusic ()
Render music for siren and pickup sound /*.
void RenderBGM ()
Render music for the background /*.
void RenderMission ()
Render music for the games /*.
void RenderMission2 ()
void RenderModelGlenn ()
void RenderQuadOnScreen (Mesh *mesh, float x_size, float y_size, float x, float y)
Render out all the dailogue boxes adn UI /*.
void ReadFromText ()
Render allow read text file /*.
void RenderModelBlue ()
Render the moving blue NPC /*.
void RenderModelOrange ()
Render the moving orange NPC /*.
void RenderModelPink ()
Render the moving pink NPC /*.
void RenderModelRed ()
Render the moving red NPC /*.
void RenderModelYellow ()
Render the moving yellow NPC /*.
void RenderModelVehicles ()
Render the vehicles and its animations /*.
void RenderStaticAIGlenn ()
Render the static NPCs where u can talk to /*.
virtual void Init ()
Initialize define our variables and also call all other Init and initialise our lights /*.
virtual void Update (double dt)
Update to call all other update functions and also update the games and scenerios in our program /*.
virtual void Render ()
Render all of our games and a combine of all render fuctions in here /*.
virtual void Exit ()
Render Exit program /*.
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Static Public Attributes
static bool bReset = false
Private Types
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_COSCUTOFF,
U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION, U_LIGHT1_COLOR,
U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ,
U_LIGHTENABLED, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_COSCUTOFF,
U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_NUMLIGHTS, U_COLOR_TEXTURE_ENABLED,
U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR, U_UI_ENABLED,
U_UI_COLOR, U_TOTAL
}
enum GEOMETRY_TYPE {
GEO_BOTTOM_L1, GEO_LEFT_L1, GEO_RIGHT_L1, GEO_FRONT_L1,
GEO_BACK_L1, GEO_APPLE, GEO_ORANGE, GEO_WATERMELON,
GEO_CABBAGE, GEO_COCONUT, GEO_LODIN, GEO_ICECREAM,
GEO_REGISTER, GEO_BASKET, GEO_COOLER, GEO_CEILING,
GEO_CASHIER, GEO_UI, GEO_MOUTAIN, GEO_TOP2,
GEO_LEFT2, GEO_RIGHT2, GEO_FRONT2, GEO_BACK2,
GEO_CHAR, GEO_TENT, GEO_DOORMAN, GEO_SHELF,
GEO_TRAVELATORUP, GEO_TRAVELATORDN, GEO_BARRIER, GEO_PACKET,
GEO_BOX1, GEO_CAN1, GEO_ARROW, GEO_SWITCH,
GEO_LIFT, GEO_DOOR, GEO_ALARM, GEO_LIGHTBALL,
GEO_BUILDING, GEO_PINKAI, GEO_BLUEAI, GEO_ORANGEAI,
GEO_YELLOWAI, GEO_REDAI, GEO_TEXT, GEO_CAR,
GEO_CAR2, GEO_CAR3, GEO_CAR4, GEO_TRUCK,
GEO_BUS, NUM_GEOMETRY
}
enum SKYBOX_TYPE {
SKYBOX_FRONT, SKYBOX_BACK, SKYBOX_LEFT, SKYBOX_RIGHT,
SKYBOX_UP, SKYBOX_DOWN, SKYBOX_EXTEBANNER, SKYBOX_EXTESIDE,
NUM_SKYBOX
}
enum CAMERA_TYPE { PLAYER_CAM, NOCLIP_CAM, NUM_CAMERA }
enum MODEL_TYPE_BLUE {
MODEL_BODY_BLUE = 0, MODEL_LEFTARM_BLUE, MODEL_LEFTFIST_BLUE, MODEL_LEFT_LEG_UPPER_BLUE,
MODEL_LEFT_LEG_LOWER_BLUE, MODEL_RIGHTARM_BLUE, MODEL_RIGHTFIST_BLUE, MODEL_RIGHT_LEG_UPPER_BLUE,
MODEL_RIGHT_LEG_LOWER_BLUE, NUM_MODEL_BLUE
}
enum MODEL_TYPE_ORANGE {
MODEL_BODY_ORANGE = 0, MODEL_LEFTARM_ORANGE, MODEL_LEFTFIST_ORANGE, MODEL_LEFT_LEG_UPPER_ORANGE,
MODEL_LEFT_LEG_LOWER_ORANGE, MODEL_RIGHTARM_ORANGE, MODEL_RIGHTFIST_ORANGE, MODEL_RIGHT_LEG_UPPER_ORANGE,
MODEL_RIGHT_LEG_LOWER_ORANGE, NUM_MODEL_ORANGE
}
enum MODEL_TYPE_PINK {
MODEL_BODY_PINK = 0, MODEL_LEFTARM_PINK, MODEL_LEFTFIST_PINK, MODEL_LEFT_LEG_UPPER_PINK,
MODEL_LEFT_LEG_LOWER_PINK, MODEL_RIGHTARM_PINK, MODEL_RIGHTFIST_PINK, MODEL_RIGHT_LEG_UPPER_PINK,
MODEL_RIGHT_LEG_LOWER_PINK, NUM_MODEL_PINK
}
enum MODEL_TYPE_RED {
MODEL_BODY_RED = 0, MODEL_LEFTARM_RED, MODEL_LEFTFIST_RED, MODEL_LEFT_LEG_UPPER_RED,
MODEL_LEFT_LEG_LOWER_RED, MODEL_RIGHTARM_RED, MODEL_RIGHTFIST_RED, MODEL_RIGHT_LEG_UPPER_RED,
MODEL_RIGHT_LEG_LOWER_RED, NUM_MODEL_RED
}
enum MODEL_TYPE_YELLOW {
MODEL_BODY_YELLOW = 0, MODEL_LEFTARM_YELLOW, MODEL_LEFTFIST_YELLOW, MODEL_LEFT_LEG_UPPER_YELLOW,
MODEL_LEFT_LEG_LOWER_YELLOW, MODEL_RIGHTARM_YELLOW, MODEL_RIGHTFIST_YELLOW, MODEL_RIGHT_LEG_UPPER_YELLOW,
MODEL_RIGHT_LEG_LOWER_YELLOW, NUM_MODEL_YELLOW
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
Render out lightings on all of our materials /*.
Private Attributes
Mesh * meshList [NUM_GEOMETRY]
Mesh * skyboxList [NUM_SKYBOX]
Mesh * modelList2 [NUM_MODEL_BLUE]
Mesh * modelList6 [NUM_MODEL_ORANGE]
Mesh * modelList7 [NUM_MODEL_PINK]
Mesh * modelList3 [NUM_MODEL_RED]
Mesh * modelList4 [NUM_MODEL_YELLOW]
unsigned m_vertexArrayID
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Vector3 charPos
Vector3 charDir
float yaw
float yaw2
Mtx44 rot
bool open
bool close
float DX
float DX2
float eley
float LiftDoor
float LiftDoor2
float waitTime
float waitTime2
float waitTime3
float waitTime4
bool up
bool down
bool Lopen
bool Lclose
bool Lopen2
bool Lclose2
bool buttonPress
bool buttonPress2
bool buttonPress3
bool buttonPress4
bool travel
bool travelDwn
bool musicAlarm
bool loop1
bool loop2
bool musicStop
bool musicStop2
bool musicBGM
bool musicCrowd
bool Mission
bool Mission2
bool coin
bool lightson
bool lightsoff
bool startfire
bool endfire
bool entrance
bool exit1
int timerez
bool open2
bool close2
float D2X
float D2X2
float rotateAngle
float translateX
float translateY
float translateZ
float transarrowY
vector< Vector3 > sphere
vector< float > radius
bool collideT
bool collideG
CAMERA_TYPE camType
FPC noClipCamera
FPC playerCamera
Light lights [2]
MS modelStack
MS viewStack
MS projectionStack
vector< CObjects > ObjectList
CObjects Skybox1
CObjects Skybox2
CObjects Basket
CObjects Cooler
CObjects Shelf
CObjects Travellator
CObjects Cashier
CObjects Elevator
CObjects Register
CObjects Barrier
CObjects firealarm
CObjects House
CObjects PickUp1
CObjects PickUp2
CObjects PickUp3
CObjects PickUp4
CObjects PickUp5
CObjects PickUp6
CObjects PickUp7
CObjects scenerio3
CObjects light
int FPS
float ET
float timer
float aitimer1
float aitimer2
float aitimer3
bool render1
bool render2
bool render3
bool render4
bool render5
bool render6
bool render7
bool render8
bool renderscenerio3
bool renderscenerio3text
bool startgame
bool game3
bool gameover1
bool place1
bool place2
bool place3
bool place4
bool place5
bool gameover
bool congrat
bool caught
bool ai1
bool ai2
bool ai3
bool renderai1text
bool renderai1text_2
bool renderai2text
bool renderai2text_2
bool renderai3text
bool renderai3text_2
bool start1
bool start2
bool start3
float openStart
CObjects modelPink
int pinkSize
vector< bool > pinkCheck
vector< float > pinkMove
float pinkTime0
float pinkTime1
float pinkTime2
CObjects modelBlue
int blueSize
vector< bool > blueCheck
vector< float > blueMove
float blueTime0
float blueTime1
float blueTime2
CObjects modelOrange
int orangeSize
vector< bool > orangeCheck
vector< float > orangeMove
float orangeTime0
float orangeTime1
float orangeTime2
CObjects modelYellow
int yellowSize
vector< bool > yellowCheck
vector< float > yellowMove
CObjects modelRed
int redSize
vector< bool > redCheck
vector< float > redMove
double speedAI
bool gameStart
bool gameEnd
float gameTime
bool isPaused
int iChoice
Detailed Description
SceneAssignment class.
Class SceneAssignment: Scene
Definition at line 32 of file SceneAssignment.h.
Member Enumeration Documentation
enum SceneAssignment::CAMERA_TYPE private
Enumerator
PLAYER_CAM
NOCLIP_CAM
NUM_CAMERA
Definition at line 160 of file SceneAssignment.h.
enum SceneAssignment::GEOMETRY_TYPE private
Enumerator
GEO_BOTTOM_L1
GEO_LEFT_L1
GEO_RIGHT_L1
GEO_FRONT_L1
GEO_BACK_L1
GEO_APPLE
GEO_ORANGE
GEO_WATERMELON
GEO_CABBAGE
GEO_COCONUT
GEO_LODIN
GEO_ICECREAM
GEO_REGISTER
GEO_BASKET
GEO_COOLER
GEO_CEILING
GEO_CASHIER
GEO_UI
GEO_MOUTAIN
GEO_TOP2
GEO_LEFT2
GEO_RIGHT2
GEO_FRONT2
GEO_BACK2
GEO_CHAR
GEO_TENT
GEO_DOORMAN
GEO_SHELF
GEO_TRAVELATORUP
GEO_TRAVELATORDN
GEO_BARRIER
GEO_PACKET
GEO_BOX1
GEO_CAN1
GEO_ARROW
GEO_SWITCH
GEO_LIFT
GEO_DOOR
GEO_ALARM
GEO_LIGHTBALL
GEO_BUILDING
GEO_PINKAI
GEO_BLUEAI
GEO_ORANGEAI
GEO_YELLOWAI
GEO_REDAI
GEO_TEXT
GEO_CAR
GEO_CAR2
GEO_CAR3
GEO_CAR4
GEO_TRUCK
GEO_BUS
NUM_GEOMETRY
Definition at line 83 of file SceneAssignment.h.
enum SceneAssignment::MODEL_TYPE_BLUE private
Enumerator
MODEL_BODY_BLUE
MODEL_LEFTARM_BLUE
MODEL_LEFTFIST_BLUE
MODEL_LEFT_LEG_UPPER_BLUE
MODEL_LEFT_LEG_LOWER_BLUE
MODEL_RIGHTARM_BLUE
MODEL_RIGHTFIST_BLUE
MODEL_RIGHT_LEG_UPPER_BLUE
MODEL_RIGHT_LEG_LOWER_BLUE
NUM_MODEL_BLUE
Definition at line 168 of file SceneAssignment.h.
enum SceneAssignment::MODEL_TYPE_ORANGE private
Enumerator
MODEL_BODY_ORANGE
MODEL_LEFTARM_ORANGE
MODEL_LEFTFIST_ORANGE
MODEL_LEFT_LEG_UPPER_ORANGE
MODEL_LEFT_LEG_LOWER_ORANGE
MODEL_RIGHTARM_ORANGE
MODEL_RIGHTFIST_ORANGE
MODEL_RIGHT_LEG_UPPER_ORANGE
MODEL_RIGHT_LEG_LOWER_ORANGE
NUM_MODEL_ORANGE
Definition at line 183 of file SceneAssignment.h.
enum SceneAssignment::MODEL_TYPE_PINK private
Enumerator
MODEL_BODY_PINK
MODEL_LEFTARM_PINK
MODEL_LEFTFIST_PINK
MODEL_LEFT_LEG_UPPER_PINK
MODEL_LEFT_LEG_LOWER_PINK
MODEL_RIGHTARM_PINK
MODEL_RIGHTFIST_PINK
MODEL_RIGHT_LEG_UPPER_PINK
MODEL_RIGHT_LEG_LOWER_PINK
NUM_MODEL_PINK
Definition at line 198 of file SceneAssignment.h.
enum SceneAssignment::MODEL_TYPE_RED private
Enumerator
MODEL_BODY_RED
MODEL_LEFTARM_RED
MODEL_LEFTFIST_RED
MODEL_LEFT_LEG_UPPER_RED
MODEL_LEFT_LEG_LOWER_RED
MODEL_RIGHTARM_RED
MODEL_RIGHTFIST_RED
MODEL_RIGHT_LEG_UPPER_RED
MODEL_RIGHT_LEG_LOWER_RED
NUM_MODEL_RED
Definition at line 212 of file SceneAssignment.h.
enum SceneAssignment::MODEL_TYPE_YELLOW private
Enumerator
MODEL_BODY_YELLOW
MODEL_LEFTARM_YELLOW
MODEL_LEFTFIST_YELLOW
MODEL_LEFT_LEG_UPPER_YELLOW
MODEL_LEFT_LEG_LOWER_YELLOW
MODEL_RIGHTARM_YELLOW
MODEL_RIGHTFIST_YELLOW
MODEL_RIGHT_LEG_UPPER_YELLOW
MODEL_RIGHT_LEG_LOWER_YELLOW
NUM_MODEL_YELLOW
Definition at line 226 of file SceneAssignment.h.
enum SceneAssignment::SKYBOX_TYPE private
Enumerator
SKYBOX_FRONT
SKYBOX_BACK
SKYBOX_LEFT
SKYBOX_RIGHT
SKYBOX_UP
SKYBOX_DOWN
SKYBOX_EXTEBANNER
SKYBOX_EXTESIDE
NUM_SKYBOX
Definition at line 147 of file SceneAssignment.h.
enum SceneAssignment::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHTENABLED
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_UI_ENABLED
U_UI_COLOR
U_TOTAL
Definition at line 34 of file SceneAssignment.h.
Constructor & Destructor Documentation
SceneAssignment::SceneAssignment ()
Definition at line 44 of file SceneAssignment.cpp.
SceneAssignment::~SceneAssignment ()
Definition at line 48 of file SceneAssignment.cpp.
Member Function Documentation
void SceneAssignment::Exit () virtual
Render Exit program /*.
Implements Scene.
Definition at line 5679 of file SceneAssignment.cpp.
void SceneAssignment::Init () virtual
Initialize define our variables and also call all other Init and initialise our lights /*.
Implements Scene.
Definition at line 1118 of file SceneAssignment.cpp.
References Math::DegreeToRadian(), FPS, MeshBuilder::GenerateText(), Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, LoadShaders(), LoadTGA(), Mtx44::SetToPerspective(), translateX, and translateZ.
void SceneAssignment::InitAI ()
Initialize the combined parts of the body for our scripted movement NPCs /*.
Definition at line 1055 of file SceneAssignment.cpp.
void SceneAssignment::InitCollision ()
Initialize add some collision for most of our large objects /*.
Definition at line 642 of file SceneAssignment.cpp.
void SceneAssignment::InitExtSkybox ()
Initialize the quards that produce the landscape ooutside of the suermarket /*.
Definition at line 610 of file SceneAssignment.cpp.
References MeshBuilder::GenerateQuad(), and LoadTGA().
void SceneAssignment::InitLevel1 ()
Initialize the walls and doors used for level 1 /*.
Definition at line 57 of file SceneAssignment.cpp.
References MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), and LoadTGA().
void SceneAssignment::InitLevel2 ()
Initialize the walls and doors used for level 2 /*.
Definition at line 117 of file SceneAssignment.cpp.
References MeshBuilder::GenerateQuad(), and LoadTGA().
void SceneAssignment::InitModelBlue ()
Initialize the individual parts of the body for our blue NPC /*.
Definition at line 396 of file SceneAssignment.cpp.
References MeshBuilder::GenerateOBJ(), and LoadTGA().
void SceneAssignment::InitModelOrange ()
Initialize the individual parts of the body for our orange NPC /*.
Definition at line 439 of file SceneAssignment.cpp.
References MeshBuilder::GenerateOBJ(), and LoadTGA().
void SceneAssignment::InitModelPink ()
Initialize the individual parts of the body for our pink NPC /*.
Definition at line 482 of file SceneAssignment.cpp.
References MeshBuilder::GenerateOBJ(), and LoadTGA().
void SceneAssignment::InitModelRed ()
Initialize the individual parts of the body for our red NPC /*.
Definition at line 525 of file SceneAssignment.cpp.
References MeshBuilder::GenerateOBJ(), and LoadTGA().
void SceneAssignment::InitModelYellow ()
Initialize the individual parts of the body for our yellow NPC /*.
Definition at line 567 of file SceneAssignment.cpp.
References MeshBuilder::GenerateOBJ(), and LoadTGA().
void SceneAssignment::InitObjects ()
Initialize all the objects that are going to be used in the program /*.
Definition at line 165 of file SceneAssignment.cpp.
References MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), and LoadTGA().
void SceneAssignment::ReadFromText ()
Render allow read text file /*.
Definition at line 4941 of file SceneAssignment.cpp.
void SceneAssignment::Render () virtual
Render all of our games and a combine of all render fuctions in here /*.
Implements Scene.
Definition at line 5090 of file SceneAssignment.cpp.
References Collision(), FPS, Application::IsKeyPressed(), Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, irrklang::ISoundEngine::play2D(), irrklang::ISoundEngine::setAllSoundsPaused(), irrklang::ISoundEngine::stopAllSounds(), Position::x, and Vector3::x.
void SceneAssignment::RenderBGM ()
Render music for the background /*.
Definition at line 4894 of file SceneAssignment.cpp.
References irrklang::ISoundEngine::play3D(), and irrklang::ISoundEngine::setRolloffFactor().
void SceneAssignment::RenderChar ()
Render static NPCs at the cash register /*.
Definition at line 4233 of file SceneAssignment.cpp.
void SceneAssignment::RenderLargeObjects ()
Render out all the large objects such as the shelves and cashier for both levels /*.
Definition at line 2452 of file SceneAssignment.cpp.
void SceneAssignment::RenderLeftColumn ()
Render the cereal boxes at the leftr column of level 2 /*.
Definition at line 3026 of file SceneAssignment.cpp.
void SceneAssignment::RenderLevel1 ()
Render the walls and doors for level 1 /*.
Definition at line 2363 of file SceneAssignment.cpp.
void SceneAssignment::RenderLevel2 ()
Render out the walls and doors for level 2 /*.
Definition at line 2417 of file SceneAssignment.cpp.
void SceneAssignment::RenderMesh (Mesh * mesh, bool enableLight) private
Render out lightings on all of our materials /*.
Definition at line 2315 of file SceneAssignment.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, Mesh::material, Component::r, Mesh::Render(), and Mesh::textureID.
void SceneAssignment::RenderMiddleColumn ()
Render the cereal boxes at the middle column of level 2 /*.
Definition at line 3539 of file SceneAssignment.cpp.
void SceneAssignment::RenderMission ()
Render music for the games /*.
Definition at line 4914 of file SceneAssignment.cpp.
References irrklang::ISoundEngine::play2D(), irrklang::ISoundEngine::setAllSoundsPaused(), and irrklang::ISoundEngine::setRolloffFactor().
void SceneAssignment::RenderMission2 ()
Definition at line 4925 of file SceneAssignment.cpp.
References irrklang::ISoundEngine::play2D(), irrklang::ISoundEngine::setAllSoundsPaused(), and irrklang::ISoundEngine::setRolloffFactor().
void SceneAssignment::RenderModelBlue ()
Render the moving blue NPC /*.
Definition at line 4366 of file SceneAssignment.cpp.
References AImoveX(), AImoveZ(), AIrotate(), and AIstop().
void SceneAssignment::RenderModelGlenn ()
void SceneAssignment::RenderModelOrange ()
Render the moving orange NPC /*.
Definition at line 4463 of file SceneAssignment.cpp.
References AImoveX(), AImoveY(), AImoveZ(), AIrotate(), and AIstop().
void SceneAssignment::RenderModelPink ()
Render the moving pink NPC /*.
Definition at line 4251 of file SceneAssignment.cpp.
References AImoveX(), AImoveZ(), AIrotate(), and AIstop().
void SceneAssignment::RenderModelRed ()
Render the moving red NPC /*.
Definition at line 4564 of file SceneAssignment.cpp.
References AImoveX(), AImoveZ(), AIrotate(), and AIstop().
void SceneAssignment::RenderModels ()
Render call the render model functions at the top in here like a compile /*.
Definition at line 4767 of file SceneAssignment.cpp.
void SceneAssignment::RenderModelVehicles ()
Render the vehicles and its animations /*.
Definition at line 4716 of file SceneAssignment.cpp.
References rotateAngle, translateX, and translateZ.
void SceneAssignment::RenderModelYellow ()
Render the moving yellow NPC /*.
Definition at line 4643 of file SceneAssignment.cpp.
References AImoveX(), AImoveZ(), AIrotate(), and AIstop().
void SceneAssignment::RenderMusic ()
Render music for siren and pickup sound /*.
Definition at line 4866 of file SceneAssignment.cpp.
References irrklang::ISoundEngine::play2D(), irrklang::ISoundEngine::play3D(), irrklang::ISoundEngine::setRolloffFactor(), and irrklang::ISoundEngine::stopAllSounds().
void SceneAssignment::RenderOut_Skybox ()
Render the exterior skyboxes,moutains and houses outside of the supermarket /*.
Definition at line 4100 of file SceneAssignment.cpp.
void SceneAssignment::RenderQuadOnScreen (Mesh * mesh, float x_size, float y_size, float x, float y)
Render out all the dailogue boxes adn UI /*.
Definition at line 4969 of file SceneAssignment.cpp.
References Mtx44::a, Mesh::Render(), Mtx44::SetToOrtho(), and Mesh::textureID.
void SceneAssignment::RenderRightColumn ()
Render the cereal boxes at the right column of level 2 /*.
Definition at line 2513 of file SceneAssignment.cpp.
void SceneAssignment::RenderSmallObjects ()
Render the fruits and ice cream at level 1 /*.
Definition at line 3775 of file SceneAssignment.cpp.
void SceneAssignment::RenderStaticAIGlenn ()
Render the static NPCs where u can talk to /*.
Definition at line 5011 of file SceneAssignment.cpp.
void SceneAssignment::RenderText (Mesh * mesh, std::string text, Color color)
Render a function that enable text rendering in the world space /*.
Definition at line 4790 of file SceneAssignment.cpp.
References Mtx44::a, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), and Mesh::textureID.
void SceneAssignment::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y)
Render a function that enable text rendering on screen /*.
Definition at line 4821 of file SceneAssignment.cpp.
References Mtx44::a, Color::r, Mesh::Render(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), and Mesh::textureID.
void SceneAssignment::Update (double dt) virtual
Update to call all other update functions and also update the games and scenerios in our program /*.
Implements Scene.
Definition at line 1765 of file SceneAssignment.cpp.
References Collision(), FPS, Application::IsKeyPressed(), irrklang::ISoundEngine::play2D(), Application::returnWindowSize(), rotateAngle, irrklang::ISoundEngine::setAllSoundsPaused(), irrklang::ISoundEngine::setListenerPosition(), Application::SetMouseinput(), irrklang::ISoundEngine::stopAllSounds(), translateX, and translateZ.
void SceneAssignment::UpdateDoor (double dt)
Update the exit and entrance door for the player and moving NPCs to enter and exit /*.
Definition at line 1525 of file SceneAssignment.cpp.
References irrklang::ISoundEngine::play2D().
void SceneAssignment::UpdateLift (double dt)
Update the lift movement and the lift door also /*.
Definition at line 1379 of file SceneAssignment.cpp.
References Application::IsKeyPressed().
void SceneAssignment::UpdateLight (double dt)
Update the light effect when there is fire alarm /*.
Definition at line 1678 of file SceneAssignment.cpp.
References Application::IsKeyPressed(), and LSPEED.
void SceneAssignment::UpdateModel (double dt)
void SceneAssignment::UpdateModelGlenn (double dt)
Walking animation of moving NPCs /*.
Definition at line 1752 of file SceneAssignment.cpp.
References ROTATE_SPEED.
void SceneAssignment::UpdateStaticAIGlenn (double dt)
void SceneAssignment::UpdateTravel (double dt)
Update the player and moving NPCs to be able to use the travelator /*.
Definition at line 1698 of file SceneAssignment.cpp.
void SceneAssignment::UpdateViewMode (double dt)
Update all of our different viewmode such as wireframe mode /*.
Definition at line 1363 of file SceneAssignment.cpp.
References Application::IsKeyPressed().
Field Documentation
bool SceneAssignment::ai1 private
Definition at line 385 of file SceneAssignment.h.
bool SceneAssignment::ai2 private
Definition at line 385 of file SceneAssignment.h.
bool SceneAssignment::ai3 private
Definition at line 385 of file SceneAssignment.h.
float SceneAssignment::aitimer1 private
Definition at line 381 of file SceneAssignment.h.
float SceneAssignment::aitimer2 private
Definition at line 381 of file SceneAssignment.h.
float SceneAssignment::aitimer3 private
Definition at line 381 of file SceneAssignment.h.
CObjects SceneAssignment::Barrier private
Definition at line 376 of file SceneAssignment.h.
CObjects SceneAssignment::Basket private
Definition at line 376 of file SceneAssignment.h.
vector<bool> SceneAssignment::blueCheck private
Definition at line 399 of file SceneAssignment.h.
vector<float> SceneAssignment::blueMove private
Definition at line 400 of file SceneAssignment.h.
int SceneAssignment::blueSize private
Definition at line 398 of file SceneAssignment.h.
float SceneAssignment::blueTime0 private
Definition at line 401 of file SceneAssignment.h.
float SceneAssignment::blueTime1 private
Definition at line 401 of file SceneAssignment.h.
float SceneAssignment::blueTime2 private
Definition at line 401 of file SceneAssignment.h.
bool SceneAssignment::bReset = false static
Definition at line 243 of file SceneAssignment.h.
Referenced by Application::Run().
bool SceneAssignment::buttonPress private
Definition at line 337 of file SceneAssignment.h.
bool SceneAssignment::buttonPress2 private
Definition at line 337 of file SceneAssignment.h.
bool SceneAssignment::buttonPress3 private
Definition at line 337 of file SceneAssignment.h.
bool SceneAssignment::buttonPress4 private
Definition at line 337 of file SceneAssignment.h.
CAMERA_TYPE SceneAssignment::camType private
Definition at line 365 of file SceneAssignment.h.
CObjects SceneAssignment::Cashier private
Definition at line 376 of file SceneAssignment.h.
bool SceneAssignment::caught private
Definition at line 384 of file SceneAssignment.h.
Vector3 SceneAssignment::charDir private
Definition at line 316 of file SceneAssignment.h.
Vector3 SceneAssignment::charPos private
Definition at line 315 of file SceneAssignment.h.
bool SceneAssignment::close private
Definition at line 322 of file SceneAssignment.h.
bool SceneAssignment::close2 private
Definition at line 350 of file SceneAssignment.h.
bool SceneAssignment::coin private
Definition at line 343 of file SceneAssignment.h.
bool SceneAssignment::collideG private
Definition at line 363 of file SceneAssignment.h.
bool SceneAssignment::collideT private
Definition at line 363 of file SceneAssignment.h.
bool SceneAssignment::congrat private
Definition at line 384 of file SceneAssignment.h.
CObjects SceneAssignment::Cooler private
Definition at line 376 of file SceneAssignment.h.
float SceneAssignment::D2X private
Definition at line 351 of file SceneAssignment.h.
float SceneAssignment::D2X2 private
Definition at line 352 of file SceneAssignment.h.
bool SceneAssignment::down private
Definition at line 332 of file SceneAssignment.h.
float SceneAssignment::DX private
Definition at line 323 of file SceneAssignment.h.
float SceneAssignment::DX2 private
Definition at line 324 of file SceneAssignment.h.
CObjects SceneAssignment::Elevator private
Definition at line 376 of file SceneAssignment.h.
float SceneAssignment::eley private
Definition at line 327 of file SceneAssignment.h.
bool SceneAssignment::endfire private
Definition at line 344 of file SceneAssignment.h.
bool SceneAssignment::entrance private
Definition at line 345 of file SceneAssignment.h.
float SceneAssignment::ET private
Definition at line 381 of file SceneAssignment.h.
bool SceneAssignment::exit1 private
Definition at line 345 of file SceneAssignment.h.
CObjects SceneAssignment::firealarm private
Definition at line 376 of file SceneAssignment.h.
int SceneAssignment::FPS private
Definition at line 380 of file SceneAssignment.h.
bool SceneAssignment::game3 private
Definition at line 383 of file SceneAssignment.h.
bool SceneAssignment::gameEnd private
Definition at line 424 of file SceneAssignment.h.
bool SceneAssignment::gameover private
Definition at line 384 of file SceneAssignment.h.
bool SceneAssignment::gameover1 private
Definition at line 383 of file SceneAssignment.h.
bool SceneAssignment::gameStart private
Definition at line 424 of file SceneAssignment.h.
float SceneAssignment::gameTime private
Definition at line 425 of file SceneAssignment.h.
CObjects SceneAssignment::House private
Definition at line 376 of file SceneAssignment.h.
int SceneAssignment::iChoice private
Definition at line 430 of file SceneAssignment.h.
bool SceneAssignment::isPaused private
Definition at line 429 of file SceneAssignment.h.
bool SceneAssignment::Lclose private
Definition at line 334 of file SceneAssignment.h.
bool SceneAssignment::Lclose2 private
Definition at line 336 of file SceneAssignment.h.
float SceneAssignment::LiftDoor private
Definition at line 328 of file SceneAssignment.h.
float SceneAssignment::LiftDoor2 private
Definition at line 329 of file SceneAssignment.h.
CObjects SceneAssignment::light private
Definition at line 376 of file SceneAssignment.h.
Light SceneAssignment::lights[2] private
Definition at line 368 of file SceneAssignment.h.
bool SceneAssignment::lightsoff private
Definition at line 343 of file SceneAssignment.h.
bool SceneAssignment::lightson private
Definition at line 343 of file SceneAssignment.h.
bool SceneAssignment::loop1 private
Definition at line 343 of file SceneAssignment.h.
bool SceneAssignment::loop2 private
Definition at line 343 of file SceneAssignment.h.
bool SceneAssignment::Lopen private
Definition at line 333 of file SceneAssignment.h.
bool SceneAssignment::Lopen2 private
Definition at line 335 of file SceneAssignment.h.
unsigned SceneAssignment::m_parameters[U_TOTAL] private
Definition at line 312 of file SceneAssignment.h.
unsigned SceneAssignment::m_programID private
Definition at line 311 of file SceneAssignment.h.
unsigned SceneAssignment::m_vertexArrayID private
Definition at line 310 of file SceneAssignment.h.
Mesh* SceneAssignment::meshList[NUM_GEOMETRY] private
Definition at line 303 of file SceneAssignment.h.
bool SceneAssignment::Mission private
Definition at line 343 of file SceneAssignment.h.
bool SceneAssignment::Mission2 private
Definition at line 343 of file SceneAssignment.h.
CObjects SceneAssignment::modelBlue private
Definition at line 397 of file SceneAssignment.h.
Mesh* SceneAssignment::modelList2[NUM_MODEL_BLUE] private
Definition at line 305 of file SceneAssignment.h.
Mesh* SceneAssignment::modelList3[NUM_MODEL_RED] private
Definition at line 308 of file SceneAssignment.h.
Mesh* SceneAssignment::modelList4[NUM_MODEL_YELLOW] private
Definition at line 309 of file SceneAssignment.h.
Mesh* SceneAssignment::modelList6[NUM_MODEL_ORANGE] private
Definition at line 306 of file SceneAssignment.h.
Mesh* SceneAssignment::modelList7[NUM_MODEL_PINK] private
Definition at line 307 of file SceneAssignment.h.
CObjects SceneAssignment::modelOrange private
Definition at line 403 of file SceneAssignment.h.
CObjects SceneAssignment::modelPink private
Definition at line 391 of file SceneAssignment.h.
CObjects SceneAssignment::modelRed private
Definition at line 414 of file SceneAssignment.h.
MS SceneAssignment::modelStack private
Definition at line 372 of file SceneAssignment.h.
CObjects SceneAssignment::modelYellow private
Definition at line 409 of file SceneAssignment.h.
bool SceneAssignment::musicAlarm private
Definition at line 343 of file SceneAssignment.h.
bool SceneAssignment::musicBGM private
Definition at line 343 of file SceneAssignment.h.
bool SceneAssignment::musicCrowd private
Definition at line 343 of file SceneAssignment.h.
bool SceneAssignment::musicStop private
Definition at line 343 of file SceneAssignment.h.
bool SceneAssignment::musicStop2 private
Definition at line 343 of file SceneAssignment.h.
FPC SceneAssignment::noClipCamera private
Definition at line 366 of file SceneAssignment.h.
vector<CObjects> SceneAssignment::ObjectList private
Definition at line 374 of file SceneAssignment.h.
bool SceneAssignment::open private
Definition at line 321 of file SceneAssignment.h.
bool SceneAssignment::open2 private
Definition at line 349 of file SceneAssignment.h.
float SceneAssignment::openStart private
Definition at line 389 of file SceneAssignment.h.
vector<bool> SceneAssignment::orangeCheck private
Definition at line 405 of file SceneAssignment.h.
vector<float> SceneAssignment::orangeMove private
Definition at line 406 of file SceneAssignment.h.
int SceneAssignment::orangeSize private
Definition at line 404 of file SceneAssignment.h.
float SceneAssignment::orangeTime0 private
Definition at line 407 of file SceneAssignment.h.
float SceneAssignment::orangeTime1 private
Definition at line 407 of file SceneAssignment.h.
float SceneAssignment::orangeTime2 private
Definition at line 407 of file SceneAssignment.h.
CObjects SceneAssignment::PickUp1 private
Definition at line 376 of file SceneAssignment.h.
CObjects SceneAssignment::PickUp2 private
Definition at line 376 of file SceneAssignment.h.
CObjects SceneAssignment::PickUp3 private
Definition at line 376 of file SceneAssignment.h.
CObjects SceneAssignment::PickUp4 private
Definition at line 376 of file SceneAssignment.h.
CObjects SceneAssignment::PickUp5 private
Definition at line 376 of file SceneAssignment.h.
CObjects SceneAssignment::PickUp6 private
Definition at line 376 of file SceneAssignment.h.
CObjects SceneAssignment::PickUp7 private
Definition at line 376 of file SceneAssignment.h.
vector<bool> SceneAssignment::pinkCheck private
Definition at line 393 of file SceneAssignment.h.
vector<float> SceneAssignment::pinkMove private
Definition at line 394 of file SceneAssignment.h.
int SceneAssignment::pinkSize private
Definition at line 392 of file SceneAssignment.h.
float SceneAssignment::pinkTime0 private
Definition at line 395 of file SceneAssignment.h.
float SceneAssignment::pinkTime1 private
Definition at line 395 of file SceneAssignment.h.
float SceneAssignment::pinkTime2 private
Definition at line 395 of file SceneAssignment.h.
bool SceneAssignment::place1 private
Definition at line 384 of file SceneAssignment.h.
bool SceneAssignment::place2 private
Definition at line 384 of file SceneAssignment.h.
bool SceneAssignment::place3 private
Definition at line 384 of file SceneAssignment.h.
bool SceneAssignment::place4 private
Definition at line 384 of file SceneAssignment.h.
bool SceneAssignment::place5 private
Definition at line 384 of file SceneAssignment.h.
FPC SceneAssignment::playerCamera private
Definition at line 367 of file SceneAssignment.h.
MS SceneAssignment::projectionStack private
Definition at line 372 of file SceneAssignment.h.
vector<float> SceneAssignment::radius private
Definition at line 362 of file SceneAssignment.h.
vector<bool> SceneAssignment::redCheck private
Definition at line 416 of file SceneAssignment.h.
vector<float> SceneAssignment::redMove private
Definition at line 417 of file SceneAssignment.h.
int SceneAssignment::redSize private
Definition at line 415 of file SceneAssignment.h.
CObjects SceneAssignment::Register private
Definition at line 376 of file SceneAssignment.h.
bool SceneAssignment::render1 private
Definition at line 383 of file SceneAssignment.h.
bool SceneAssignment::render2 private
Definition at line 383 of file SceneAssignment.h.
bool SceneAssignment::render3 private
Definition at line 383 of file SceneAssignment.h.
bool SceneAssignment::render4 private
Definition at line 383 of file SceneAssignment.h.
bool SceneAssignment::render5 private
Definition at line 383 of file SceneAssignment.h.
bool SceneAssignment::render6 private
Definition at line 383 of file SceneAssignment.h.
bool SceneAssignment::render7 private
Definition at line 383 of file SceneAssignment.h.
bool SceneAssignment::render8 private
Definition at line 383 of file SceneAssignment.h.
bool SceneAssignment::renderai1text private
Definition at line 386 of file SceneAssignment.h.
bool SceneAssignment::renderai1text_2 private
Definition at line 386 of file SceneAssignment.h.
bool SceneAssignment::renderai2text private
Definition at line 386 of file SceneAssignment.h.
bool SceneAssignment::renderai2text_2 private
Definition at line 386 of file SceneAssignment.h.
bool SceneAssignment::renderai3text private
Definition at line 386 of file SceneAssignment.h.
bool SceneAssignment::renderai3text_2 private
Definition at line 386 of file SceneAssignment.h.
bool SceneAssignment::renderscenerio3 private
Definition at line 383 of file SceneAssignment.h.
bool SceneAssignment::renderscenerio3text private
Definition at line 383 of file SceneAssignment.h.
Mtx44 SceneAssignment::rot private
Definition at line 318 of file SceneAssignment.h.
float SceneAssignment::rotateAngle private
Definition at line 355 of file SceneAssignment.h.
Referenced by RenderModelVehicles(), and Update().
CObjects SceneAssignment::scenerio3 private
Definition at line 376 of file SceneAssignment.h.
CObjects SceneAssignment::Shelf private
Definition at line 376 of file SceneAssignment.h.
CObjects SceneAssignment::Skybox1 private
Definition at line 376 of file SceneAssignment.h.
CObjects SceneAssignment::Skybox2 private
Definition at line 376 of file SceneAssignment.h.
Mesh* SceneAssignment::skyboxList[NUM_SKYBOX] private
Definition at line 304 of file SceneAssignment.h.
double SceneAssignment::speedAI private
Definition at line 421 of file SceneAssignment.h.
vector<Vector3> SceneAssignment::sphere private
Definition at line 361 of file SceneAssignment.h.
bool SceneAssignment::start1 private
Definition at line 387 of file SceneAssignment.h.
bool SceneAssignment::start2 private
Definition at line 387 of file SceneAssignment.h.
bool SceneAssignment::start3 private
Definition at line 387 of file SceneAssignment.h.
bool SceneAssignment::startfire private
Definition at line 344 of file SceneAssignment.h.
bool SceneAssignment::startgame private
Definition at line 383 of file SceneAssignment.h.
float SceneAssignment::timer private
Definition at line 381 of file SceneAssignment.h.
int SceneAssignment::timerez private
Definition at line 346 of file SceneAssignment.h.
float SceneAssignment::transarrowY private
Definition at line 359 of file SceneAssignment.h.
float SceneAssignment::translateX private
Definition at line 356 of file SceneAssignment.h.
Referenced by Init(), RenderModelVehicles(), and Update().
float SceneAssignment::translateY private
Definition at line 357 of file SceneAssignment.h.
float SceneAssignment::translateZ private
Definition at line 358 of file SceneAssignment.h.
Referenced by Init(), RenderModelVehicles(), and Update().
bool SceneAssignment::travel private
Definition at line 340 of file SceneAssignment.h.
bool SceneAssignment::travelDwn private
Definition at line 341 of file SceneAssignment.h.
CObjects SceneAssignment::Travellator private
Definition at line 376 of file SceneAssignment.h.
bool SceneAssignment::up private
Definition at line 331 of file SceneAssignment.h.
MS SceneAssignment::viewStack private
Definition at line 372 of file SceneAssignment.h.
float SceneAssignment::waitTime private
Definition at line 330 of file SceneAssignment.h.
float SceneAssignment::waitTime2 private
Definition at line 330 of file SceneAssignment.h.
float SceneAssignment::waitTime3 private
Definition at line 330 of file SceneAssignment.h.
float SceneAssignment::waitTime4 private
Definition at line 330 of file SceneAssignment.h.
float SceneAssignment::yaw private
Definition at line 317 of file SceneAssignment.h.
float SceneAssignment::yaw2 private
Definition at line 317 of file SceneAssignment.h.
vector<bool> SceneAssignment::yellowCheck private
Definition at line 411 of file SceneAssignment.h.
vector<float> SceneAssignment::yellowMove private
Definition at line 412 of file SceneAssignment.h.
int SceneAssignment::yellowSize private
Definition at line 410 of file SceneAssignment.h.
The documentation for this class was generated from the following files:
Application/Source/SceneAssignment.h
Application/Source/SceneAssignment.cpp