My Application: MeshBuilder Class Reference
MeshBuilder Class Reference
Provides methods to generate mesh of different shapes.
#include <MeshBuilder.h>
Static Public Member Functions
static Mesh * GenerateAxes (const std::string &meshName, float lengthX, float lengthY, float lengthZ)
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateQuad (const std::string &meshName, Color color, float length)
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCube (const std::string &meshName, Color color, float length=1.f)
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCircle (const std::string &meshname, Color color, unsigned numSlice, float radius)
static Mesh * GenerateRing (const std::string &meshname, Color color, unsigned numSlice, float outerR, float innerR)
static Mesh * GenerateSphere (const std::string &meshName, Color color, unsigned numStack, unsigned numSlice, float radius)
static Mesh * GenerateHemisSphere (const std::string &meshName, Color color, unsigned numStackh, unsigned numSliceh, float radiush)
static Mesh * GenerateCylinder (const std::string &meshname, Color color, unsigned numstack, unsigned numSlice, float radius, float height)
static Mesh * GenerateOBJ (const std::string &meshName, const std::string &file_path)
static Mesh * GenerateText (const std::string &meshName, unsigned numRow, unsigned numCol)
Detailed Description
Provides methods to generate mesh of different shapes.
Class MeshBuilder:
Definition at line 22 of file MeshBuilder.h.
Member Function Documentation
Mesh * MeshBuilder::GenerateAxes (const std::string & meshName, float lengthX, float lengthY, float lengthZ) static
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - x-axis should start at -lengthX / 2 and end at lengthX / 2
lengthY - y-axis should start at -lengthY / 2 and end at lengthY / 2
lengthZ - z-axis should start at -lengthZ / 2 and end at lengthZ / 2
Returns
Pointer to mesh storing VBO/IBO of reference axes
Definition at line 30 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), Color::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCircle (const std::string & meshname, Color color, unsigned numSlice, float radius) static
Definition at line 246 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCube (const std::string & meshName, Color color, float length = 1.f) static
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of cube
lengthY - height of cube
lengthZ - depth of cube
Returns
Pointer to mesh storing VBO/IBO of cube
Definition at line 164 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateCylinder (const std::string & meshname, Color color, unsigned numstack, unsigned numSlice, float radius, float height) static
Definition at line 477 of file MeshBuilder.cpp.
References Vertex::color, CylinderX(), CylinderZ(), Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateHemisSphere (const std::string & meshName, Color color, unsigned numStackh, unsigned numSliceh, float radiush) static
Definition at line 423 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, HsphereX(), HsphereY(), HsphereZ(), Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateOBJ (const std::string & meshName, const std::string & file_path) static
Definition at line 521 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, IndexVBO(), LoadOBJ(), Mesh::mode, and Mesh::vertexBuffer.
Referenced by SceneAssignment::InitModelBlue(), SceneAssignment::InitModelOrange(), SceneAssignment::InitModelPink(), SceneAssignment::InitModelRed(), SceneAssignment::InitModelYellow(), and SceneAssignment::InitObjects().
Mesh * MeshBuilder::GenerateQuad (const std::string & meshName, Color color, float length) static
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of quad
lengthY - height of quad
Returns
Pointer to mesh storing VBO/IBO of quad
Definition at line 87 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), TexCoord::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by SceneAssignment::InitExtSkybox(), SceneAssignment::InitLevel1(), SceneAssignment::InitLevel2(), and SceneAssignment::InitObjects().
Mesh * MeshBuilder::GenerateRing (const std::string & meshname, Color color, unsigned numSlice, float outerR, float innerR) static
Definition at line 300 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateSphere (const std::string & meshName, Color color, unsigned numStack, unsigned numSlice, float radius) static
Definition at line 368 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), sphereX(), sphereY(), sphereZ(), and Mesh::vertexBuffer.
Referenced by SceneAssignment::InitLevel1().
Mesh * MeshBuilder::GenerateText (const std::string & meshName, unsigned numRow, unsigned numCol) static
Definition at line 550 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), TexCoord::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by SceneAssignment::Init().
The documentation for this class was generated from the following files:
Application/Source/MeshBuilder.h
Application/Source/MeshBuilder.cpp