My Application: Application Class Reference
Application Class Reference
Application class.
#include <Application.h>
Public Member Functions
Application ()
~Application ()
void Init ()
Logic for Application to work.
void Run ()
Run these codes when Application is running.
void Exit ()
Destroy everything before exiting.
Static Public Member Functions
static bool IsKeyPressed (unsigned short key)
React to key pressed by user.
static int returnWindowSize (bool X)
Return Window size.
static double GetMouseinput (bool X)
React to mouse input by user.
static void SetMouseinput (double X, double Y)
Define initial Mouse input.
static void SetCursor (int i)
Define initial cursor.
Private Attributes
StopWatch m_timer
Detailed Description
Application class.
Class Application:
Definition at line 21 of file Application.h.
Constructor & Destructor Documentation
Application::Application ()
Definition at line 142 of file Application.cpp.
Application::~Application ()
Definition at line 146 of file Application.cpp.
Member Function Documentation
void Application::Exit ()
Destroy everything before exiting.
Definition at line 250 of file Application.cpp.
References m_window.
Referenced by main().
double Application::GetMouseinput (bool X) static
React to mouse input by user.
Definition at line 81 of file Application.cpp.
References m_window.
Referenced by FPC::Update().
void Application::Init ()
Logic for Application to work.
Definition at line 155 of file Application.cpp.
References error_callback(), m_window, and resize_callback().
Referenced by main().
bool Application::IsKeyPressed (unsigned short key) static
React to key pressed by user.
Definition at line 71 of file Application.cpp.
Referenced by SceneAssignment::Render(), Camera3::Update(), Camera::Update(), FPC::Update(), SceneAssignment::Update(), SceneAssignment::UpdateLift(), SceneAssignment::UpdateLight(), and SceneAssignment::UpdateViewMode().
int Application::returnWindowSize (bool X) static
Return Window size.
Definition at line 128 of file Application.cpp.
References m_window.
Referenced by FPC::Update(), and SceneAssignment::Update().
void Application::Run ()
Run these codes when Application is running.
Definition at line 213 of file Application.cpp.
References SceneAssignment::bReset, Scene::Exit(), frameTime, StopWatch::getElapsedTime(), Scene::Init(), m_timer, m_window, Scene::Render(), StopWatch::startTimer(), Scene::Update(), and StopWatch::waitUntil().
Referenced by main().
void Application::SetCursor (int i) static
Define initial cursor.
Definition at line 111 of file Application.cpp.
References m_window.
void Application::SetMouseinput (double X, double Y) static
Define initial Mouse input.
Definition at line 101 of file Application.cpp.
References m_window.
Referenced by FPC::Update(), and SceneAssignment::Update().
Field Documentation
StopWatch Application::m_timer private
Definition at line 38 of file Application.h.
Referenced by Run().
The documentation for this class was generated from the following files:
Application/Source/Application.h
Application/Source/Application.cpp