My Application: Application/Source/functions.cpp File Reference
functions.cpp File Reference
Detect collision.
#include "functions.h"
Functions
bool Collision (Vector3 charPos, std::vector< CObjects > objList)
Collision positions.
bool Collision (Vector3 charPos, std::vector< CObjects > objList, int obj, int pos)
Collision detections.
Detailed Description
Detect collision.
Author
Lim Wei Heng
Definition in file functions.cpp.
Function Documentation
bool Collision (Vector3 charPos, std::vector< CObjects > objList)
Collision positions.
Definition at line 17 of file functions.cpp.
Referenced by SceneAssignment::Render(), FPC::Update(), and SceneAssignment::Update().
bool Collision (Vector3 charPos, std::vector< CObjects > objList, int obj, int pos)
Collision detections.
Definition at line 40 of file functions.cpp.