My Application: Application/Source/LoadTGA.h File Reference
LoadTGA.h File Reference
Load TGA files for textures.
#include <GL\glew.h>
Functions
GLuint LoadTGA (const char *file_path)
Detailed Description
Load TGA files for textures.
Author
Andy Chan
Definition in file LoadTGA.h.
Function Documentation
GLuint LoadTGA (const char * file_path)
Definition at line 8 of file LoadTGA.cpp.
Referenced by SceneAssignment::Init(), SceneAssignment::InitExtSkybox(), SceneAssignment::InitLevel1(), SceneAssignment::InitLevel2(), SceneAssignment::InitModelBlue(), SceneAssignment::InitModelOrange(), SceneAssignment::InitModelPink(), SceneAssignment::InitModelRed(), SceneAssignment::InitModelYellow(), and SceneAssignment::InitObjects().