My Application: Application/Source/MeshBuilder.cpp File Reference
MeshBuilder.cpp File Reference
Build Meshes here.
#include "MeshBuilder.h"
#include <GL\glew.h>
#include <vector>
#include "Vertex.h"
#include "MyMath.h"
#include "LoadOBJ.h"
Functions
float sphereX (float phi, float theta)
float sphereY (float phi, float theta)
float sphereZ (float phi, float theta)
float HsphereX (float phi, float theta)
float HsphereY (float phi, float theta)
float HsphereZ (float phi, float theta)
float CylinderX (float theta)
float CylinderZ (float theta)
Detailed Description
Build Meshes here.
Author
Andy Chan
Definition in file MeshBuilder.cpp.
Function Documentation
float CylinderX (float theta)
Definition at line 469 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateCylinder().
float CylinderZ (float theta)
Definition at line 473 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateCylinder().
float HsphereX (float phi, float theta)
Definition at line 414 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateHemisSphere().
float HsphereY (float phi, float theta)
Definition at line 417 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateHemisSphere().
float HsphereZ (float phi, float theta)
Definition at line 420 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateHemisSphere().
float sphereX (float phi, float theta)
Definition at line 359 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateSphere().
float sphereY (float phi, float theta)
Definition at line 362 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateSphere().
float sphereZ (float phi, float theta)
Definition at line 365 of file MeshBuilder.cpp.
References Math::DegreeToRadian().
Referenced by MeshBuilder::GenerateSphere().