My Application: Application/Source/MoveAI.h File Reference
MoveAI.h File Reference
Movement of NPCs.
#include "MatrixStack.h"
#include "Vector3.h"
Functions
bool AImoveZ (MS &model, float &zero, float val, float speed=1)
NPC movement across Z-axis.
bool AImoveX (MS &model, float &zero, float val, float speed=1)
NPC movement across X-axis.
bool AImoveY (MS &model, float &zero, float val, float speed=1)
NPC movement across Y-axis.
bool AIstop (float &zero, float val, float speed=1)
Stop NPC from moving.
bool AIrotate (MS &model, Vector3 &pos, float &zero, char axis, float val, float speed=2)
Rotate NPC.
Detailed Description
Movement of NPCs.
Author
Lim Wei Heng
Definition in file MoveAI.h.
Function Documentation
bool AImoveX (MS & model, float & zero, float val, float speed = 1)
NPC movement across X-axis.
Definition at line 49 of file MoveAI.cpp.
References MS::Translate().
Referenced by SceneAssignment::RenderModelBlue(), SceneAssignment::RenderModelOrange(), SceneAssignment::RenderModelPink(), SceneAssignment::RenderModelRed(), and SceneAssignment::RenderModelYellow().
bool AImoveY (MS & model, float & zero, float val, float speed = 1)
NPC movement across Y-axis.
Definition at line 80 of file MoveAI.cpp.
References MS::Translate().
Referenced by SceneAssignment::RenderModelOrange().
bool AImoveZ (MS & model, float & zero, float val, float speed = 1)
NPC movement across Z-axis.
Definition at line 18 of file MoveAI.cpp.
References MS::Translate().
Referenced by SceneAssignment::RenderModelBlue(), SceneAssignment::RenderModelOrange(), SceneAssignment::RenderModelPink(), SceneAssignment::RenderModelRed(), and SceneAssignment::RenderModelYellow().
bool AIrotate (MS & model, Vector3 & pos, float & zero, char axis, float val, float speed = 2)
Rotate NPC.
Definition at line 128 of file MoveAI.cpp.
References MS::Rotate(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by SceneAssignment::RenderModelBlue(), SceneAssignment::RenderModelOrange(), SceneAssignment::RenderModelPink(), SceneAssignment::RenderModelRed(), and SceneAssignment::RenderModelYellow().
bool AIstop (float & zero, float val, float speed = 1)
Stop NPC from moving.
Definition at line 112 of file MoveAI.cpp.
Referenced by SceneAssignment::RenderModelBlue(), SceneAssignment::RenderModelOrange(), SceneAssignment::RenderModelPink(), SceneAssignment::RenderModelRed(), and SceneAssignment::RenderModelYellow().